### ISSUE TITLE
CardDetail Userstory

### ISSUE THREAD

**Issue by zimb0o** [zimb0o/capstone-project#4]
## Value proposition

as a user
i want to see the details of a card
so i can see more information about the pointed card

## Description

![2E79A20E-7168-4C2B-AC57-D9EB4D349385_1_201_a](https://github.com/zimb0o/capstone-project/assets/126156598/2e41694c-c339-4753-a9a3-cde328f1201e)

## Acceptance criteria
- card has a "Details" button
- by clicking on "weitere details",  shows "equipment, tasks,"
- li for the different tasks 
- by clicking the "schließen" button, the details section will disappear

## Tasks

- create a feature branch
- add "Details" button to CardComponent
  -add logic to show details section on button click
   - Equipment
   - Tasks
   - "schließen" Button
      - add logic to hide details section on button click

**Comment by PacoSchwab** [comment]
Nice US, but I don't get the point of "the "weitere details" infos should be more visibile then the cardinfo the spot". I think you should specify what should be visible and how you want elements to be "more" visible than others (fontSize etc.).

**Comment by zimb0o** [comment]
Thank you, you are right. The "weitere details" are not necessary in this US. I specified the visibility of the elements.
