### ISSUE TITLE
favorite spots

### ISSUE THREAD

**Issue by zimb0o** [zimb0o/capstone-project#8]
## Value proposition

as a user
i want to highlight my favorite spots 
so i can choose between my common spots 

## Description

![059432EF-90A4-4DE9-9BED-2BEDED6069BD_1_201_a](https://user-images.githubusercontent.com/126156598/237023494-e90035c8-a793-45ab-9edc-efcc42c7f6b6.jpeg)

## Acceptance criteria

- The spot card includes a button to mark the spot as a favorite 
   - The button is represented by a ❤️ and can be toggled between marked and unmarked states.

- The application features a page for favorite spots.
   - The page is titled "Favorites".

- Only cards with marked ❤️ are displayed on this page.

- The navigation includes a ❤️ icon.

- Clicking on the ❤️ icon will navigate to the favorites page.

## Tasks

- create a feature/favorites
- create favorites page
   -  add headline "Favorites"
- add ❤️   as a link with logic function, which link to 
favorites page
- the ❤️ icon is toggle as marked/unmarked on spot card
- the marked ❤️ card is shown on the favorites page

**Comment by HenrikeStahlhut** [comment]
LGTM ✌🏻
